docs:
	@notatio coi --command="${BASE_NAME} code uml --help" --document-path=README.md --header='`uml`' --limiter-left=### --limiter-right="### " --index=1
	@notatio coi --command="${BASE_NAME} code dep --help" --document-path=README.md --header='`dep`' --limiter-left=### --limiter-right="## " --index=1
